= docker-packaging

image:https://img.shields.io/docker/pulls/jenkinsciinfra/repo-proxy?label=jenkinsciinfra%repo-proxy&logo=docker&logoColor=white[link="https://hub.docker.com/r/jenkinsciinfra/repo-proxy"]

This repository contains everything needed to build a docker image for caching artefacts from repo.jenkins-ci.org repository to accelerate builds.

== Running the service

Start a local Docker container (running in background) based on this image with:

[source,bash]
----
docker run --rm --name local-artifact-cacher -p 80:80 --detach jenkinssciinfra/repo-proxy # should add a tag in production
----

Cached object should return a status code `200` with HEADER `X-Cache-Status` set to `HIT` or `MISS`

[source,bash]
----
curl -I http://localhost/releases/cf/pgmann/plugins/url-auth-sso/1.0/url-auth-sso-1.0-javadoc.jar
----

Snapshot artifacts shouldn't be cached and thus return a status code `200` without HEADER `X-Cache-Status`

[source,bash]
----
curl -I http://localhost/snapshots/jenkins/repository/1.1-SNAPSHOT/repository-1.1-20140112.102452-1-javadoc.jar
----

maven-metadata.xml object should return a status code `200` without HEADER `X-Cache-Status`

[source,bash]
--
curl -I http://localhost/snapshots/com/deveo/plugins/deveo/maven-metadata.xml
--


[IMPORTANT]
All requests should return a status code `200` "OK"

[IMPORTANT]
--
Cached requests contain HEADER `X-Cache-Status` set to:

* `HIT` if it got its response from cache
* `MISS` if it didn't got its response from cache
--

== Contribute

If you want to contribute, or build/test the Docker Image, please refer to the following documentation about Docker images for the Jenkins Infra project: link:https://github.com/jenkins-infra/pipeline-library/blob/master/resources/io/jenkins/infra/docker/README.adoc[README]
